train:
  _target_: datasets.rirs.SimulatedRIRTrain
  num_samples: 10_000
  segment_length: 32000
  fs: 16000
  t60_range: [0.4, 1.0]
  dim_range: [5, 15, 5, 15, 2, 6]
  min_distance_to_wall: 1.
  normalize: True
  align: True
 
  #random seed
  seed: 0

test:
  _target_: datasets.rirs.SimulatedRIRTest
  # path: /data/lemercier/databases/rir_simulated_aligned/rir/tt
  segment_length: 32000
  fs: 16000
  t60_range: [0.4, 1.0]
  dim_range: [5, 15, 5, 15, 2, 6]
  min_distance_to_wall: 1.
  normalize: True
  align: True
  num_examples: 16
 
  #random seed
  seed: 0