train:
  _target_: datasets.rirs.RealRIRTrain
  path: /scratch/elec/t412-asp/arni
  num_samples: 10_000
  segment_length: 16384
  fs: 16000
  normalize: True
  align: True
 
  #random seed
  seed: 0

test:
  _target_: datasets.rirs.RealRIRTest
  path: /scratch/elec/t412-asp/arni
  segment_length: 16384
  fs: 16000
  normalize: True
  align: True
  num_examples: 16
 
  #random seed
  seed: 0
