train:
  _target_: datasets.rirs.RealRIRTrain
  path: /data/lemercier/databases/RIRs_organized
  num_samples: 10_000
  segment_length: 32000
  fs: 16000
  normalize: True
  align: True
 
  #random seed
  seed: 0

test:
  _target_: datasets.rirs.RealRIRTest
  path: /data/lemercier/databases/RIRs_organized
  segment_length: 32000
  fs: 16000
  normalize: True
  align: True
  num_examples: 16
 
  #random seed
  seed: 0
