train:
  _target_: datasets.vctk.VCTKTrain
  segment_length: 65536
  fs: 16000
  path: /scratch/elec/t412-asp/audio_datasets/speech/VCTK/wav16
  speakers_discard: ["p280", "p315"]
  speakers_test: ["p351", "p360", "p361", "p362", "p363", "p364", "p374", "p376"]
  normalize: False
  #sigma_data: 0.05 #for normalization purposes
 
  #random seed
  seed: 0

test:
  _target_: datasets.vctk.VCTKTest
  segment_length: 65536
  fs: 16000
  path: /scratch/elec/t412-asp/audio_datasets/speech/VCTK/wav16
  speakers_discard: ["p280", "p315"]
  speakers_test: ["p351", "p360", "p361", "p362", "p363", "p364", "p374", "p376"]
  normalize: False
  #sigma_data: 0.05 #for normalization purposes
  num_examples: 16
 
  #random seed
  seed: 0
